test:
	g++ parser.cpp ppm.cpp ray.cpp sphere.cpp  tinyxml2.cpp   tester.cpp -o tester -std=c++11
all:
	g++   shape.cpp mesh.cpp parser.cpp ppm.cpp ray.cpp sphere.cpp triangle.cpp tinyxml2.cpp raytracer.cpp -o raytracer -std=c++11
clean:
	rm raytracer
